name: "Scrapper"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 */8 * * *"

jobs:
  deploy-webapp:
    name: "Scrap and update DB"
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./scrapper
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: "Install dependencies"
        run: npm ci
      - name: "Run script"
        run: npm start
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
